
spring:
  application:
    name: gs-spring-data-reactive-redis
  redis:
    client-name: gs-spring-data-reactive-redis
#    client-type: lettuce
    host: localhost
    port: 6379
    connect-timeout: 3S
    timeout: 1S
#    lettuce:
#      pool:
#        enabled: true
#        max-active: 8
#        max-idle: 8
#        min-idle: 4
#        max-wait: 3s
#      shutdown-timeout: 3s
